volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command:
      - --transaction-isolation=READ-COMMITTED
      - --log-bin=binlog
      - --binlog-format=ROW
      - --max_allowed_packet=256M
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --innodb_buffer_pool_size=512M
    volumes:
      - db:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=**
      - MYSQL_PASSWORD=**
      - MYSQL_DATABASE=n**
      - MYSQL_USER=**
  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
      - /mnt/omv_share:/mnt/omv_share
    environment:
      - MYSQL_PASSWORD=**
      - MYSQL_DATABASE=**
      - MYSQL_USER=**
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --appendonly yes
    